#!/usr/bin/env python3
"""CV-X-IF integration stage — the sibling of scaiev.py for cores whose ISAX is
attached over the CORE-V-XIF eXtension interface instead of being spliced into
the pipeline by SCAIE-V.

run_cvxif() plays run_scaiev()'s role: it populates `out_dir/<core>/` with a
self-contained integrated design —

  1. a copy of the pristine upstream core checkout (deps/ stays untouched),
  2. required core patches applied to that copy,
  3. the glue + coprocessor wrapper generated by tools/cvxif_glue_gen.py from
     the Longnail ISAX YAML,
  4. the per-core top (core + coprocessor on the interface),
  5. a `filelist.f` (sources, +incdir+, +define+) for downstream consumers.

Simulation is the regular cocotb flow (simulation.py): each top presents the
interface of the corresponding SCAIE-V top, so SCAIE-V's own `testbench`
wrapper (get_tb_wrapper_files()) and memory map drive it.
"""
import glob
import os
import shutil
import subprocess

import error
import run_cmd
import scaiev
from scaiev import CoreSupport


class CVXIFCoreSupport(CoreSupport):
    """Base class for cores integrated by cvxif.py.

    Centralizes what the CV-X-IF cores share: no SCAIE-V hooks, the CVXIF
    interface datasheet, no SCAL wrapper top, and (for now) no cocotb flow.
    Concrete cores add the pristine checkout location, the glue-generator
    wrapper flavor, required core patches, the top module, and the expansion
    of the core's own source manifest.
    """

    def uses_cvxif(self) -> bool:
        return True

    def has_isax_support(self) -> bool:
        # No SCAIE-V hooks: the ISAX arrives over CV-X-IF.
        return False

    def get_longnail_datasheet_name(self) -> str:
        # The interface, not a pipeline: see docs/cvxif.md.
        return "CVXIF.yaml"

    def get_maketop(self) -> str:
        # SCAIE-V's maketop rewrites a wrapper with SCAL pins; there are none.
        return ""

    def run_extra_build_steps(self, target_dir, kconf_syms) -> None:
        pass

    def get_tb_env_vars(self, kconf_syms) -> list[str]:
        return []

    def get_core_srcs(self, scal_sources, core_dir):
        """Synthesis-consumer contract (the synthesis plugins): sources of
        the integrated design from the filelist.f run_cvxif wrote.

        Also the cocotb contract (simulation.py): `get_tb_wrapper_files()` names
        the `testbench` wrapper, one of SCAIE-V's (relative to its maketop dir,
        like every SCAIE-V core) -- the tops present the interface of the
        corresponding SCAIE-V top for that. A core that does not provide one
        yet can still be synthesized: the tb fields stay empty, which
        simulation.run_tb refuses. `scal_sources` is ignored (no SCAL).
        Entries outside the integrated tree (../ISAX_*.sv, ../splitop_*.sv)
        are dropped: both the synthesis plugins and simulation.py glob the
        out_dir-level ISAX sources themselves.
        """
        filelist = os.path.join(core_dir, "filelist.f")
        if not os.path.isfile(filelist):
            raise NotImplementedError(
                f"{type(self).__name__}: no {filelist} — run_cvxif must run "
                f"first")
        srcs, incdirs, defines = [], [], []
        with open(filelist) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                if line.startswith("+define+"):
                    defines.append(line[len("+define+"):])
                elif line.startswith("+incdir+"):
                    incdirs.append(line[len("+incdir+"):])
                elif line.startswith(".."):
                    continue
                else:
                    srcs.append(line)
        try:
            tb_srcs = list(self.get_tb_wrapper_files())
        except NotImplementedError:
            tb_srcs = []
        return (tb_srcs, srcs, "testbench" if tb_srcs else "", self.get_top_module(),
                incdirs, defines, self.get_sim_makefile_args())

    # ---- CV-X-IF hooks ----------------------------------------------------

    def get_upstream_core_dir(self) -> str:
        """The pristine upstream checkout under deps/ this core builds from."""
        raise NotImplementedError

    def cvxif_glue_args(self) -> list[str]:
        """Per-core wrapper flags for tools/cvxif_glue_gen.py."""
        return []

    def get_core_patches(self) -> list[str]:
        """Patches (patch -p1 format) required on the copied core sources."""
        return []

    def get_top_files(self) -> list[str]:
        """Top-level SV files (core + coprocessor on the interface) copied
        into the integrated tree. The first entry is the top module."""
        raise NotImplementedError

    def get_top_module(self) -> str:
        """Module name of the top in get_top_files()[0]: the name the SCAIE-V
        testbench wrapper of get_tb_wrapper_files() instantiates."""
        raise NotImplementedError

    def get_tb_wrapper_files(self) -> list[str]:
        """cocotb testbench wrapper sources (module `testbench`), relative to
        SCAIE-V's util/maketop: the wrapper of the corresponding SCAIE-V core,
        whose top interface this core's CV-X-IF top presents. It exposes the
        bus ports `get_tb_env_vars()` names."""
        raise NotImplementedError

    def get_sim_makefile_args(self) -> dict[str, str]:
        """Extra cocotb Makefile lines, keyed by simulator ("default" = all)."""
        return {}

    def get_cvxif_core_filelist(self, core_dir) -> tuple[list[str], list[str], list[str]]:
        """Expand the core's own source manifest in `core_dir`.

        Returns (sources, include dirs, defines), all paths relative to
        `core_dir`.
        """
        raise NotImplementedError


def _kconf_y(kconf_syms, name) -> bool:
    return name in kconf_syms and kconf_syms[name].str_value == "y"


def _apply_core_patch(target_dir, patch_file):
    """Apply `patch_file` to the copied core tree, tolerating a checkout that
    already carries it (a checkout patched in place)."""
    patch_file = os.path.abspath(patch_file)
    if not os.path.isfile(patch_file):
        error.exit_error(f"CV-X-IF core patch not found: {patch_file}", error.USER_ERROR)
    reverse_check = subprocess.run(f"patch -p1 -R --dry-run -s -f < {patch_file}",
                                   shell=True, cwd=target_dir, capture_output=True)
    if reverse_check.returncode == 0:
        print(f" - Core patch already applied: {os.path.basename(patch_file)}")
        return
    print(f" - Applying core patch {os.path.basename(patch_file)}")
    run_cmd.run(target_dir, f"patch -p1 -s -f < {patch_file}",
                f"Could not apply CV-X-IF core patch {patch_file}", error.CVXIF_BASE + 1)


def run_cvxif(core, isax_desc, out_dir, kconf_syms):
    print("Invoking CV-X-IF integration:")
    core_support = scaiev.get_core_support(core)
    target_dir = os.path.abspath(f"{out_dir}/{core}")
    os.makedirs(target_dir, exist_ok=True)

    isax_desc = os.path.abspath(isax_desc)
    isax_file = os.path.basename(isax_desc)
    # NO_ISAX entry point (entrypoint.py hands us its empty NO_ISAX.yaml):
    # no glue to generate, the top ties the interface off instead.
    no_isax = (isax_file == "NO_ISAX.yaml")
    if no_isax:
        isax_name = None
    elif isax_file.startswith("ISAX_") and isax_file.endswith(".yaml"):
        isax_name = isax_file[len("ISAX_"):-len(".yaml")]
    else:
        error.exit_error(f"Unexpected ISAX YAML name '{isax_file}' (want ISAX_<name>.yaml)",
                         error.CVXIF_BASE)

    # 1. Copy the pristine upstream core into the output tree.
    core_src = core_support.get_upstream_core_dir()
    if not os.path.isdir(core_src):
        error.exit_error(f"Upstream core checkout missing: {core_src}", error.USER_ERROR)
    print(f" - Copying core sources from {core_src}")
    scaiev.copy_folder_contents(core_support, core_src, target_dir)

    # 2. Required core patches, applied to the copy (deps/ stays pristine).
    for patch in core_support.get_core_patches():
        _apply_core_patch(target_dir, patch)

    # 3. Glue + coprocessor wrapper from the Longnail ISAX YAML. Without an
    #    ISAX there is nothing to generate: the top ties the interface off
    #    itself when CVXIF_COPROC is not defined (a CPU-only baseline design).
    if no_isax:
        print(" - NO_ISAX: nothing on the interface (the top ties it off)")
    else:
        glue_args = list(core_support.cvxif_glue_args())
        # Speculative admission is the generator's default; only the opt-out is passed.
        # An ISAX with custom registers falls back on its own, so nothing to do here.
        if _kconf_y(kconf_syms, "CVXIF_NON_SPECULATIVE"):
            glue_args.append("--non-speculative")
        # Out-of-order emission and the input-buffer bypass are the generator's defaults;
        # only the opt-outs are passed. Both fall back on their own where they cannot
        # apply (an ISAX observing the interface after its WrRD; a commit-gated build).
        if _kconf_y(kconf_syms, "CVXIF_IN_ORDER_RESULT"):
            glue_args.append("--in-order-result")
        if _kconf_y(kconf_syms, "CVXIF_INPUT_BUFFER"):
            glue_args.append("--input-buffer")
        if _kconf_y(kconf_syms, "CVXIF_ALLOW_CUSTOM_REGS"):
            glue_args.append("--allow-custom-regs")
        if _kconf_y(kconf_syms, "CVXIF_GEN_PROTOCOL_TB"):
            glue_args.append("--testbench")
        print(f" - Generating CV-X-IF glue for ISAX '{isax_name}'")
        run_cmd.run(".", f"python3 tools/cvxif_glue_gen.py {' '.join(glue_args)} "
                         f"{isax_desc} -o {target_dir}",
                    "CV-X-IF glue generation failed", error.CVXIF_BASE + 2)

    # 4. The top: core + coprocessor on the interface.
    top_files = [os.path.abspath(f) for f in core_support.get_top_files()]
    for top in top_files:
        shutil.copy(top, target_dir)

    # 5. Optional core+ISAX-config specific source patches (SCV_POST_PATCH,
    #    colon-separated) — the same knob run_scaiev honors, applied to the
    #    copied tree so a configuration can e.g. strip the core's multiplier
    #    (core_patches/cv32e40x_no_mul.patch / cv32e40px_no_mul.patch) when
    #    the ISAX provides it. After the top copy, so patches may touch any
    #    file of the integrated tree.
    post_patch = kconf_syms["SCV_POST_PATCH"].str_value if "SCV_POST_PATCH" in kconf_syms else ""
    for patch_file in filter(None, post_patch.split(":")):
        _apply_core_patch(target_dir, patch_file)

    # 6. File list for downstream consumers (simulation/synthesis).
    core_srcs, incdirs, defines = core_support.get_cvxif_core_filelist(target_dir)

    # Glue, coprocessor wrapper and the copied top(s). The protocol testbench
    # (tb_cvxif_glue_*.sv) is sim-only and deliberately not matched.
    glue_srcs = sorted(os.path.basename(f)
                       for f in glob.glob(os.path.join(target_dir, "cvxif_*.sv")))
    # The coprocessor datapath: ISAX SV + any split-datapath operator modules.
    out_dir_abs = os.path.abspath(out_dir)
    isax_srcs = []
    if not no_isax:
        isax_srcs = [os.path.join(out_dir_abs, f"ISAX_{isax_name}.sv")]
        isax_srcs += sorted(set(glob.glob(os.path.join(out_dir_abs, "split*.sv")) +
                                glob.glob(os.path.join(out_dir_abs, "splitop_*.sv"))))
        isax_srcs = [os.path.relpath(p, target_dir) for p in isax_srcs]

    # The tops instantiate the coprocessor named by the CVXIF_COPROC macro and
    # tie the interface off without it -- so a missing define must not go
    # unnoticed when there IS an ISAX.
    coproc = [f for f in glue_srcs if f.startswith("cvxif_coproc_")]
    if not no_isax:
        if len(coproc) != 1:
            error.exit_error("CV-X-IF: expected exactly one generated coprocessor wrapper "
                             f"(cvxif_coproc_*.sv) in {target_dir}, found {coproc}",
                             error.CVXIF_BASE + 4)
        defines = defines + [f"CVXIF_COPROC={coproc[0][:-len('.sv')]}"]

    filelist = os.path.join(target_dir, "filelist.f")
    missing = [s for s in core_srcs + glue_srcs + isax_srcs
               if not os.path.isfile(os.path.join(target_dir, s))]
    if missing:
        error.exit_error("CV-X-IF filelist references missing sources:\n  " +
                         "\n  ".join(missing), error.CVXIF_BASE + 3)
    with open(filelist, "w") as f:
        for d in defines:
            f.write(f"+define+{d}\n")
        for i in incdirs:
            f.write(f"+incdir+{i}\n")
        for s in core_srcs + glue_srcs + isax_srcs:
            f.write(f"{s}\n")

    print(f" - CV-X-IF integrated design in {os.path.relpath(target_dir)} "
          f"({len(core_srcs)} core + {len(glue_srcs)} glue sources, filelist.f)")
    if no_isax:
        print(" - No ISAX attached: CPU-only baseline")
