#!/bin/bash
import os

def exit_error(msg):
    print(f"ERROR: {msg}")
    exit(-1)

# function to parse Kconfig file and return a dict of options
def read_kconfig():
    try:
        # open .config file generated by menuconfig
        file = open(".config")
        # somewhat complicated dict comprehension
        # we move through each line of the file (for file in line) ...
        # ... and discard comments, empty lines and disabled options (if line[0] != '#' and line != "\n" and line.split("=")[1].lower() != "n\n")
        # For lines which were not discarded, we extract the key (line.split("=")[0]).
        # For the value, we check if it is a y -> boolean option or a string and set the value accordingly (True if line.split("=")[1].lower() == "y\n" else line.split("=")[1])
        config_options = { line.split("=")[0]:(True if line.split("=")[1].lower() == "y\n" else line.split("=")[1]) for line in file if line[0] != '#' and line != "\n" and line.split("=")[1].lower() != "n\n" }
        return config_options
    except:
        exit_error("Config could not be parsed - file is missing or malformated. Re-run make menuconfig")


# discard all read kconfig entries which are not boolean
# returns list of enabled booleans
def extract_kconfig_enabled(kconfig_dict):
    return [ k for k,v in kconfig_dict.items() if v == True ]

# filter kconfig dictionary for config options related to loading MLIR files
def extract_enabled_isax_from_config(kconfig_dict):
    return { k:v for k,v in kconfig_dict.items() if k[:12] == "CONFIG_ISAX_" and k[-3:] == "_EN"}

# generate mapping from ISAX config name to isax description file
def gen_isax_map():
    isax_map = {}
    for root, dirs, files in os.walk(".", topdown=False):
        for name in files:
            if name == "paths.csv":
                csvpath = os.path.join(root, name)
                try:
                    csvfile = open(csvpath)
                    current_map = { line.split(";")[0]:line.split(";")[1].replace("\n","") for line in csvfile}
                    isax_map = {**isax_map, **current_map}
                except:
                    exit_error(f"could not parse ISAX path.csv file found in: {root}")
    return isax_map



if __name__ == "__main__":
    # read kconfig file
    kconfig_dict = read_kconfig()

    # get list of enabled ISAXes
    enabled_isaxes = extract_kconfig_enabled(extract_enabled_isax_from_config(kconfig_dict))

    # get mapping from config option to mlir files
    isax_file_mapping = gen_isax_map()

    # map enabled isaxes to LN mlir input files
    isax_input_files = None
    try:
        isax_input_files = list(map(lambda x: isax_file_mapping[x], enabled_isaxes))
    except KeyError as ke:
        exit_error(f"Could not find .mlir file for {str(ke)}. Check your paths.csv.")

    # print enabled ISAXes
    print("Building <core> with ISAXes:")
    for isax,mlir in zip(enabled_isaxes, isax_input_files):
        print(f" - {isax[12:-3]} (associated description: {mlir})")

    # invoke LN synth
    print("LN synth")

    print("SCAIE-V pain")
