#!/usr/bin/env python3
import os
import functools
import kconfiglib
import menuconfig
import shutil
import tempfile

import error
import run_cmd
import sol_sel_to_yaml


def resolve_sched_algo(kconfig_syms):
    if kconfig_syms['LN_SCHED_ALGO_MS'].str_value == "y":
        sched_algo = ""
        if kconfig_syms['LN_SCHED_ALGO_MI'].str_value == "y":
            sched_algo = "MI_"
        if kconfig_syms['LN_SCHED_ALGO_PA'].str_value == "y":
            sched_algo += "PA"
        if kconfig_syms['LN_SCHED_ALGO_RA'].str_value == "y":
            sched_algo += "RA"

        sched_algo += "MS"
        return sched_algo
    return "LEGACY"

def resolve_opty_lib(kconfig_syms):
    #TODO these options could also be autogenerated!
    if kconfig_syms['LN_OPTY_NO_MODEL'].str_value == "y":
        return ""
    if kconfig_syms['LN_OPTY_OL2_MODEL'].str_value == "y":
        return os.path.abspath("deps/longnail/opTyLibraries/OL2.yaml")
    assert kconfig_syms['LN_OPTY_CUSTOM_MODEL'].str_value == "y"
    return os.path.abspath(kconfig_syms['LN_OPTY_CUSTOM_MODEL_PATH'].str_value)

def run_longnail(mlir_paths, datasheet, kconfig_syms, out_dir):
    # gather src files
    assert len(mlir_paths) == 1
    #TODO implement LN based mlir file merging!

    # check inputs
    try:
        float(kconfig_syms['LN_CLOCK_PERIOD'].str_value)
    except ValueError:
        error.exit_error(f"Target clock period='{kconfig_syms['LN_CLOCK_PERIOD'].str_value}' could not be converted to a floating point value!")

    sched_algo = resolve_sched_algo(kconfig_syms)
    optylib = resolve_opty_lib(kconfig_syms)
    out_dir = os.path.abspath(out_dir)
    datasheet = os.path.abspath(datasheet)
    if kconfig_syms['LN_CELL_LIBRARY'].str_value:
        library = os.path.abspath(kconfig_syms['LN_CELL_LIBRARY'].str_value)
    else:
        library = ""

    sched_sol_mlir_file = os.path.join(out_dir, "scheduling_solutions.mlir")
    sched_sol_kconf_file = os.path.join(out_dir, "Kconfig")
    sched_sol_config_file = os.path.join(out_dir, ".config")
    sol_selection_file = os.path.join(out_dir, "selected_solutions.yaml")
    force_min_II_solutions = kconfig_syms['LN_FORCE_MIN_II_SOLUTIONS'].str_value == "y"

    longnail_schedule_flags = [
        "-lower-coredsl-to-lil",
        f"-max-unroll-factor={kconfig_syms['LN_MAX_LOOP_UNROLL_FACTOR'].str_value}",
        f"-schedule-lil=\"datasheet={datasheet} library={library} opTyLibrary={optylib} clockTime={kconfig_syms['LN_CLOCK_PERIOD'].str_value} schedulingAlgo={sched_algo} useCommercialSolver={'true' if kconfig_syms['LN_USE_COMMERCIAL_SOLVER'].str_value == 'y' else 'false'} schedulingTimeout={kconfig_syms['LN_SCHEDULE_TIMEOUT'].str_value} schedRefineTimeout={kconfig_syms['LN_REFINE_TIMEOUT'].str_value} solSelKconfPath={sched_sol_kconf_file}\"",
        f"-o {sched_sol_mlir_file}",
    ]


    ln_path = os.path.abspath("./deps/longnail/build/bin/longnail-opt")
    # execute LN
    isax_mlir = mlir_paths[0]
    longnail_flags_str = functools.reduce(
        lambda a, b: a+" "+b, longnail_schedule_flags)
    run_cmd.run("build", f"{ln_path} {longnail_flags_str} {isax_mlir}", f"Longnail scheduling failed", False, 200)

    if not force_min_II_solutions and os.path.exists(sched_sol_kconf_file):
        kconf = kconfiglib.Kconfig(sched_sol_kconf_file)

        # Backup the current .config file to a temporary directory
        temp_dir = tempfile.mkdtemp()
        original_config_path = '.config'
        backup_config_path = os.path.join(temp_dir, '.config_backup')
        shutil.move(original_config_path, backup_config_path)

        # open menu config to let the user select the desired solutions
        menuconfig.menuconfig(kconf)

        # Restore the .config file
        shutil.move(backup_config_path, original_config_path)
        # Clean up the temporary directory
        shutil.rmtree(temp_dir)

        # Then convert the selection to a yaml file for longnail to process
        sol_sel_to_yaml.convert_selection_to_yaml(kconf, sol_selection_file)
        # Note this is optional:
        kconf.write_config(sched_sol_config_file)
    else:
        force_min_II_solutions = True

    longnail_hw_gen_flags = [
        "-lower-lil-to-hw=forceUseMinIISolution=true" if force_min_II_solutions else f"-lower-lil-to-hw=solutionSelection={sol_selection_file}",
        "-simplify-structure", "-cse", "-canonicalize",
        "-lower-seq-to-sv", "-hw-cleanup", "-prettify-verilog", "-hw-legalize-modules",
        f"-export-split-verilog=dir-name={out_dir}", "-o /dev/null"
    ]
    longnail_flags_str = functools.reduce(
        lambda a, b: a+" "+b, longnail_hw_gen_flags)
    run_cmd.run("build", f"{ln_path} {longnail_flags_str} {sched_sol_mlir_file}", f"Longnail HW-Gen failed", False, 200)
    return isax_mlir


def build_longnail():
    # create build and tool directory
    os.makedirs("build", exist_ok=True)

    # build longnail
    if not os.path.isfile("deps/longnail/build/bin/longnail-opt"):
        print("Building Longnail...")
        run_cmd.run("deps/longnail", "OR_TOOLS_VER=9.8 ./build_deps.sh",
                    "Gathering deps for CIRCT failed")
        run_cmd.run("deps/longnail", "./build_circt.sh",
                    "Building CIRCT failed")
        run_cmd.run("deps/longnail", "./build_longnail.sh",
                    "Longnail build failed")


# Selects the core datasheet file based on selected core
# TODO: if we would make the files in LN all lowercase, we could simply generate the file name
def select_core_datasheet(kconfig_core):
    if len(kconfig_core) != 1:
        error.exit_error(
            f"No or more than one core selected in Kconfig: {kconfig_core}")
    kconfig_core = kconfig_core[0]

    if (kconfig_core == "CORE_PICORV32"):
        return "deps/longnail/datasheets/PicoRV32.yaml"
    elif (kconfig_core == "CORE_ORCA"):
        return "deps/longnail/datasheets/ORCA.yaml"
    elif (kconfig_core == "CORE_PICCOLO"):
        return "deps/longnail/datasheets/Piccolo.yaml"
    elif (kconfig_core == "CORE_VEX_4S"):
        return "deps/longnail/datasheets/VexRiscv_4s.yaml"
    elif (kconfig_core == "CORE_VEX_5S"):
        return "deps/longnail/datasheets/VexRiscv_5s.yaml"
    elif (kconfig_core == "CORE_CVA5"):
        return "deps/benchmarks/CVA5.yaml"
    else:
        error.exit_error(f"No LN datasheet for selected core '{kconfig_core}' found!")


def provide_isax_yaml(out_dir):
    filelist = open(f"{out_dir}/filelist.f")
    yamls = [f[:-1] for f in filelist if f[-6:-1] == ".yaml"]
    return f"{out_dir}/"+yamls[0]
