#!/usr/bin/env python3
import os
import functools
import kconfiglib
import menuconfig
import shutil
import tempfile

import error
import run_cmd
from tools import sol_sel_to_yaml


def resolve_solver(kconfig_syms):
    for sym in kconfig_syms:
        if kconfig_syms[sym].str_value == "y" and str(sym).startswith("LN_SOLVER_USE_"):
            return str(sym)[len("LN_SOLVER_USE_"):]
    return None


def resolve_sched_algo(kconfig_syms):
    if kconfig_syms['LN_SCHED_ALGO_MS'].str_value == "y":
        sched_algo = ""
        if kconfig_syms['LN_SCHED_ALGO_MI'].str_value == "y":
            sched_algo = "MI_"
        if kconfig_syms['LN_SCHED_ALGO_PA'].str_value == "y":
            sched_algo += "PA"
        if kconfig_syms['LN_SCHED_ALGO_RA'].str_value == "y":
            sched_algo += "RA"

        sched_algo += "MS"
        return sched_algo
    return "LEGACY"


def resolve_opty_lib(kconfig_syms):
    # TODO these options could also be autogenerated!
    if kconfig_syms['LN_OPTY_NO_MODEL'].str_value == "y":
        return ""
    if kconfig_syms['LN_OPTY_OL2_MODEL'].str_value == "y":
        return os.path.abspath("deps/longnail/opTyLibraries/OL2.yaml")
    assert kconfig_syms['LN_OPTY_CUSTOM_MODEL'].str_value == "y"
    return os.path.abspath(kconfig_syms['LN_OPTY_CUSTOM_MODEL_PATH'].str_value)


def get_longnail_bin(kconf_syms, opt_prefix = "LN", fallback_folder = "longnail"):
    if kconf_syms[f"USE_PREBUILT_{opt_prefix}"].str_value == "y":
        ln_path = os.path.abspath(kconf_syms[f"{opt_prefix}_BINARY"].str_value)

        if not os.path.exists(ln_path):
            error.exit_error(f"Specified {fallback_folder} binary path '{ln_path}' does not exist!", error.USER_ERROR)

        return ln_path
    else:
        return os.path.abspath(f"deps/{fallback_folder}/build/bin/longnail-opt")


def run_longnail(mlir_paths, datasheet, kconfig_syms, out_dir):
    # gather src files
    skip_scheduling = kconfig_syms["MLIR_ENTRY_POINT"].str_value == "y" and kconfig_syms["MLIR_ENTRY_POINT_IS_SCHEDULED"].str_value == "y"

    show_ln_output = kconfig_syms["LN_ALWAYS_SHOW_OUTPUT"].str_value == "y"

    ln_path = get_longnail_bin(kconfig_syms)
    isax_mlir = mlir_paths[0]
    if len(mlir_paths) > 1:
        concated_isax_mlir = os.path.abspath(os.path.join(out_dir, "pre_merged_isax.mlir"))
        isax_mlir = os.path.abspath(os.path.join(out_dir, "merged_isax.mlir"))
        with open(concated_isax_mlir, "w") as isax_mlir_file:
            for f in mlir_paths:
                with open(f, "r") as fo:
                    isax_mlir_file.write(fo.read())
            os.fsync(isax_mlir_file)
        run_cmd.run(out_dir, f"{ln_path} -merge-multiple-isaxes {concated_isax_mlir} -o {isax_mlir}", f"Longnail scheduling failed", error.LN_BASE + 6, show_ln_output, 200)

    # check inputs
    try:
        float(kconfig_syms['LN_CLOCK_PERIOD'].str_value)
    except ValueError:
        error.exit_error(f"Target clock period='{kconfig_syms['LN_CLOCK_PERIOD'].str_value}' could not be converted to a floating point value!", error.USER_ERROR)

    sched_algo = resolve_sched_algo(kconfig_syms)
    optylib = resolve_opty_lib(kconfig_syms)
    ilp_solver = resolve_solver(kconfig_syms)
    out_dir = os.path.abspath(out_dir)
    datasheet = os.path.abspath(datasheet)
    if kconfig_syms['LN_CELL_LIBRARY'].str_value:
        library = os.path.abspath(kconfig_syms['LN_CELL_LIBRARY'].str_value)
    else:
        library = ""

    sched_sol_mlir_file = os.path.join(out_dir, "scheduling_solutions.mlir")
    sched_sol_kconf_file = os.path.join(out_dir, "Kconfig")
    sched_sol_config_file = os.path.join(out_dir, ".config")
    sol_selection_file = os.path.join(out_dir, "selected_solutions.yaml")
    force_min_II_solutions = kconfig_syms['LN_FORCE_MIN_II_SOLUTIONS'].str_value == "y"

    verbose = "false"
    if kconfig_syms['LN_VERBOSE_SCHEDULING'].str_value == "y":
        verbose = "true"

    longnail_schedule_flags = [
        "-lower-coredsl-to-lil",
        f"-max-unroll-factor={kconfig_syms['LN_MAX_LOOP_UNROLL_FACTOR'].str_value}",
        f"-schedule-lil=\"datasheet={datasheet} library={library} opTyLibrary={optylib} clockTime={kconfig_syms['LN_CLOCK_PERIOD'].str_value} schedulingAlgo={sched_algo} solver={ilp_solver} schedulingTimeout={kconfig_syms['LN_SCHEDULE_TIMEOUT'].str_value} schedRefineTimeout={kconfig_syms['LN_REFINE_TIMEOUT'].str_value} solSelKconfPath={sched_sol_kconf_file} verbose={verbose}\"",
        f"-o {sched_sol_mlir_file}",
    ]
    if kconfig_syms['LN_DEBUG_SCHEDULING'].str_value == "y":
        longnail_schedule_flags.append("-debug-only=hw-sched")

    # execute LN
    if not skip_scheduling:
        longnail_flags_str = functools.reduce(
            lambda a, b: a+" "+b, longnail_schedule_flags)
        run_cmd.run(out_dir, f"{ln_path} {longnail_flags_str} {isax_mlir}", f"Longnail scheduling failed", error.LN_BASE + 4, show_ln_output, 200)
    else:
        sched_sol_mlir_file = os.path.abspath(kconfig_syms["MLIR_ENTRY_POINT_PATH"].str_value)
        sched_sol_kconf_file = os.path.join(os.path.dirname(sched_sol_mlir_file), "Kconfig")

    if not force_min_II_solutions and kconfig_syms['LN_PREDEFINED_SOLUTION_SELECTION'].str_value:
        sol_selection_file = os.path.abspath(kconfig_syms['LN_PREDEFINED_SOLUTION_SELECTION'].str_value)
    elif not force_min_II_solutions and os.path.exists(sched_sol_kconf_file):
        kconf = kconfiglib.Kconfig(sched_sol_kconf_file)

        # Backup the current .config file to a temporary directory
        temp_dir = tempfile.mkdtemp()
        original_config_path = '.config'
        backup_config_path = os.path.join(temp_dir, '.config_backup')
        shutil.move(original_config_path, backup_config_path)

        # open menu config to let the user select the desired solutions
        menuconfig.menuconfig(kconf)

        # Restore the .config file
        shutil.move(backup_config_path, original_config_path)
        # Clean up the temporary directory
        shutil.rmtree(temp_dir)

        # Then convert the selection to a yaml file for longnail to process
        sol_sel_to_yaml.convert_selection_to_yaml(kconf, sol_selection_file)
        # Note this is optional:
        kconf.write_config(sched_sol_config_file)
    else:
        force_min_II_solutions = True

    longnail_hw_gen_flags = [
        "-lower-lil-to-hw=forceUseMinIISolution=true" if force_min_II_solutions else f"-lower-lil-to-hw=solutionSelection={sol_selection_file}",
        "-simplify-structure", "-cse", "-canonicalize", "-print-stats",
        "-lower-seq-to-sv", "-hw-cleanup", "-prettify-verilog", "-hw-legalize-modules",
        f"-export-split-verilog=dir-name={out_dir}", "-o /dev/null"
    ]
    if kconfig_syms['LN_DEBUG_HWGEN'].str_value == "y":
        longnail_hw_gen_flags.append("-debug-only=hw-gen")
    if kconfig_syms['LN_DEBUG_PRINT_STATS'].str_value == "y":
        longnail_hw_gen_flags.append("-debug-only=print-stats")

    longnail_flags_str = functools.reduce(
        lambda a, b: a+" "+b, longnail_hw_gen_flags)
    run_cmd.run(out_dir, f"{ln_path} {longnail_flags_str} {sched_sol_mlir_file}", f"Longnail HW-Gen failed", error.LN_BASE + 5, show_ln_output, 200)
    return isax_mlir


def build_longnail(kconf_syms):
    if kconf_syms["USE_PREBUILT_LN"].str_value == "y":
        return

    # build longnail
    if not os.path.isfile("deps/longnail/build/bin/longnail-opt"):
        print("Building Longnail...")
        run_cmd.run("deps/longnail", "OR_TOOLS_VER=9.8 ./build_deps.sh",
                    "Gathering deps for CIRCT failed", error.LN_BASE + 1)
        run_cmd.run("deps/longnail", "./build_circt.sh",
                    "Building CIRCT failed", error.LN_BASE + 2)
        run_cmd.run("deps/longnail", "./build_longnail.sh",
                    "Longnail build failed", error.LN_BASE + 3)


# Selects the core datasheet file based on selected core
# TODO: if we would make the files in LN all lowercase, we could simply generate the file name
def select_core_datasheet(kconfig_core):
    if len(kconfig_core) != 1:
        error.exit_error(
            f"No or more than one core selected in Kconfig: {kconfig_core}", error.USER_ERROR)
    kconfig_core = kconfig_core[0]

    datasheet_folder = "deps/longnail/datasheets"

    if (kconfig_core == "CORE_PICORV32"):
        return f"{datasheet_folder}/PicoRV32.yaml"
    elif (kconfig_core == "CORE_ORCA"):
        return f"{datasheet_folder}/ORCA.yaml"
    elif (kconfig_core == "CORE_PICCOLO"):
        return f"{datasheet_folder}/Piccolo.yaml"
    elif (kconfig_core == "CORE_VEX_4S"):
        return f"{datasheet_folder}/VexRiscv_4s.yaml"
    elif (kconfig_core == "CORE_VEX_5S"):
        return f"{datasheet_folder}/VexRiscv_5s.yaml"
    elif (kconfig_core == "CORE_CVA5"):
        return f"{datasheet_folder}/CVA5.yaml"
    elif (kconfig_core == "CORE_CVA6"):
        return f"{datasheet_folder}/CVA6.yaml"
    else:
        error.exit_error(f"No LN datasheet for selected core '{kconfig_core}' found!", error.USER_ERROR)


def provide_isax_yaml(out_dir):
    filelist = open(f"{out_dir}/filelist.f")
    yamls = [f[:-1] for f in filelist if f[-6:-1] == ".yaml"]
    return f"{out_dir}/"+yamls[0]
