#!/usr/bin/env python3
"""Build the DOTP matrix-vector benchmark as a CV-X-IF test program.

The other generators in this directory synthesize a test: they pick operands,
run the CoreDSL->Python model for the golden values and emit `test.S`. This one
compiles a benchmark that already exists -- eval/benchmarks/dotp_matvec_{h,b}.cpp
in the paper repository -- because the point here is not to check the ISAX's
arithmetic (gen_test_xcorevsimd already does that) but to time it, and the same
source has to run on CV32E40X that runs on the four cocotb cores or the numbers
are not comparable.

    CVXIF_BENCH_SRC=<...>/dotp_matvec_h.cpp \\
    CVXIF_BENCH_EXPECTED=<...>/dotp_matvec_h_expected.txt \\
    CVXIF_ISAX_DESC=<...>/isax_analysis.yaml \\
    [CVXIF_BENCH_FLAGS=-DTB_FREE_LOOPS] \\
    tools/cvxif_sim/run.sh <design-dir> merged

What it has to bridge
---------------------
The cocotb harness gives the testbench `_test_resdata` and a result checker that
compares as many words as an expected file holds. This harness has neither: it
compares memory at RESULT_BASE against a GOLDEN array baked into the testbench.
So the benchmark's own convention is preserved by pointing `_test_resdata` at
RESULT_BASE with a linker symbol, and the expected file is translated into that
GOLDEN array.

The five cycle counts the benchmark writes after its checked words are appended
to GOLDEN as zeros, exactly as run_benchmarks.py does for the cocotb path: the
testbench then reports them as mismatches carrying the measured values, which is
the only way to read a word a golden-value checker does not expect. A run whose
only mismatches are those trailing words succeeded.

Memory map: the benchmark's static arrays (a 16x16 word matrix, its vector and
five result rows) are far larger than a generated test's, so RESULT_BASE moves
up to 0x6000 -- above the image, below the 0x8000 stack top, inside the
testbench's 64 KiB. The default 0x1000 would sit inside .bss.
"""
import os
import subprocess
import struct
import sys

# testgen_common reads the memory map from the environment at import time, so
# the override has to be in place before it is imported.
os.environ.setdefault("CVXIF_RESULT_BASE", "0x6000")

import testgen_common  # noqa: E402
from testgen_common import (  # noqa: E402
    HEX_WIDTH, MEM_BASE, MMIO_BASE, RESULT_BASE, STACK_TOP, TEXT_BASE,
    write_golden)

CLANG = sys.argv[1]
LLD = sys.argv[2]
OBJCOPY = sys.argv[3]
# argv[4] is MODEL_DIR: the CoreDSL->Python model the other generators use for
# golden values. Unused here -- the golden values come from the benchmark's
# checked-in expected file, which is what the cocotb runs are checked against.

SRC = os.environ.get("CVXIF_BENCH_SRC")
EXPECTED = os.environ.get("CVXIF_BENCH_EXPECTED")
DESC = os.environ.get("CVXIF_ISAX_DESC")
FLAGS = os.environ.get("CVXIF_BENCH_FLAGS", "")
N_CYCLE_WORDS = int(os.environ.get("CVXIF_BENCH_CYCLE_WORDS", "5"))
MARCH = os.environ.get("CVXIF_BENCH_MARCH", "rv32im_zicsr")

for name, value in (("CVXIF_BENCH_SRC", SRC), ("CVXIF_BENCH_EXPECTED", EXPECTED),
                    ("CVXIF_ISAX_DESC", DESC)):
    if not value:
        sys.exit(f"gen_test_merged: {name} is not set -- see this file's docstring")
    if not os.path.isfile(value):
        sys.exit(f"gen_test_merged: {name} does not exist: {value}")


def read_expected(path):
    """The checked words, from the benchmark's expected file (hex, # comments)."""
    words = []
    for line in open(path):
        line = line.split("#", 1)[0].strip()
        if line:
            words.append(int(line, 16))
    return words


# _start: the benchmark is a plain `main` with no runtime behind it, so this is
# the whole environment it gets -- a stack, a trap handler that skips the
# faulting instruction, and a store to the done address once main returns.
# .bss is not cleared: every array the benchmark reads is written first (the
# matrix and vector from its generator, the result rows by the kernels).
START_S = f"""\
# Generated by gen_test_merged.py
  .section .text.start
  .globl _start
_start:
  li   sp, 0x{STACK_TOP:08x}
  la   t0, trap_handler
  csrw mtvec, t0
  j    past_handler
  .balign 128                # CV32E40X: mtvec.base is WARL, 128-byte aligned
trap_handler:
  csrr t0, mepc
  addi t0, t0, 4
  csrw mepc, t0
  mret
past_handler:
  call main
  li   t0, 1
  li   t1, 0x{MMIO_BASE + 4:08x}
  sw   t0, 0(t1)           # signal completion
9:
  j    9b
"""


def emit_hex(binary):
    """test.bin -> mem.hex, same layout build_image() writes."""
    data = open(binary, "rb").read()
    pad_words = (TEXT_BASE - MEM_BASE) // 4
    assert pad_words >= 0, "CVXIF_MEM_BASE must not be above CVXIF_TEXT_BASE"
    words = [0] * pad_words
    for i in range(0, len(data), 4):
        words.append(int.from_bytes(data[i:i + 4].ljust(4, b"\0"), "little"))
    with open("mem.hex", "w") as f:
        if HEX_WIDTH == 64:
            if len(words) % 2:
                words.append(0)
            for i in range(0, len(words), 2):
                f.write(f"{words[i + 1]:08x}{words[i]:08x}\n")
        else:
            for w in words:
                f.write(f"{w:08x}\n")
    return len(data)


with open("start.S", "w") as f:
    f.write(START_S)

clangxx = CLANG + "++" if not CLANG.endswith("++") else CLANG
common = ["--target=riscv32-unknown-elf", f"-march={MARCH}", "-mabi=ilp32",
          "-nostdlib"]

subprocess.run([CLANG, *common, "-c", "start.S", "-o", "start.o"], check=True)
subprocess.run([clangxx, *common, f"-misax-desc={os.path.abspath(DESC)}",
                "-fno-exceptions", "-fno-rtti", "-O3",
                *(FLAGS.split() if FLAGS else []),
                "-c", os.path.abspath(SRC), "-o", "bench.o"], check=True)

def alloc_top(elf):
    """Highest address any allocated section occupies.

    NOT the same as the size of `objcopy -O binary`, which is what this used to
    be checked against: .bss is allocated but occupies no file space, so it sits
    ABOVE the loadable image and a check against the binary's length cannot see
    it. That is not hypothetical -- the benchmark's data array landed on the
    result region and silently overwrote one cycle count with a value that was
    physically impossible (3 cycles for a 720-instruction kernel), which only
    surfaced from a diff against an earlier run.
    """
    with open(elf, "rb") as f:
        data = f.read()
    assert data[:4] == b"\x7fELF" and data[4] == 1, f"{elf}: not ELF32"
    e_shoff, = struct.unpack_from("<I", data, 0x20)
    e_shentsize, e_shnum = struct.unpack_from("<HH", data, 0x2E)
    top = 0
    for i in range(e_shnum):
        off = e_shoff + i * e_shentsize
        sh_flags, sh_addr, _, sh_size = struct.unpack_from("<IIII", data, off + 8)
        if sh_flags & 0x2 and sh_size:           # SHF_ALLOC
            top = max(top, sh_addr + sh_size)
    return top


# `_test_resdata` is what the benchmark's getResultPtr() resolves; the cocotb
# harness provides it from a linker script, here it is simply the result base.
#
# Link twice. Nothing places the result region -- it is a --defsym at a fixed
# address with no section behind it -- so the linker is free to put .bss on top
# of it, and did. The first link is only to measure where the program actually
# ends; the region is then placed above that, and the second link bakes the
# final address into the symbol. golden.svh carries the same value, so the
# testbench reads where the program wrote.
def link(resbase):
    subprocess.run([LLD, "-m", "elf32lriscv", f"--Ttext=0x{TEXT_BASE:x}",
                    "-e", "_start", f"--defsym=_test_resdata=0x{resbase:x}",
                    "start.o", "bench.o", "-o", "test.elf"], check=True)


link(RESULT_BASE)
result_base = max(RESULT_BASE, (alloc_top("test.elf") + 15) & ~15)
if result_base != RESULT_BASE:
    link(result_base)
    testgen_common.RESULT_BASE = result_base   # what write_golden emits

subprocess.run([OBJCOPY, "-O", "binary", "test.elf", "test.bin"], check=True)
size = emit_hex("test.bin")

golden = read_expected(EXPECTED) + [0] * N_CYCLE_WORDS
end = result_base + 4 * len(golden)
if end > STACK_TOP:
    sys.exit(f"gen_test_merged: results 0x{result_base:x}..0x{end:x} reach the "
             f"stack top 0x{STACK_TOP:x} -- raise CVXIF_STACK_TOP")
if alloc_top("test.elf") > result_base:
    sys.exit(f"gen_test_merged: image ends at 0x{alloc_top('test.elf'):x}, past "
             f"the result base 0x{result_base:x}")
write_golden(golden, result_in_mem=True)
print(f"gen_test_merged: {os.path.basename(SRC)}"
      + (f" [{FLAGS}]" if FLAGS else "")
      + f" -> image {size} bytes, {len(golden)} golden words "
        f"({N_CYCLE_WORDS} of them the cycle counts, expected as zero so the "
        f"testbench reports the measured values)")
